alias: Marstek controller
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.my_cheapest_hours
    enabled: true
    from: "off"
    to: "on"
  - trigger: state
    entity_id:
      - binary_sensor.my_cheapest_hours
    enabled: true
    from: "on"
    to: "off"
  - trigger: state
    entity_id:
      - binary_sensor.expensive_hours
    to: "on"
    from: "off"
  - trigger: state
    entity_id:
      - binary_sensor.expensive_hours
    to: "off"
    from: "on"
  - trigger: numeric_state
    entity_id:
      - sensor.lilygo_rs485_marstek_battery_state_of_charge
    below: 15
    id: bijna leeg
    alias: Accu bijna leeg
conditions: []
actions:
  - action: automation.turn_off
    metadata: {}
    data:
      stop_actions: true
    target:
      label_id: marstek
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.expensive_hours
            state:
              - "on"
        sequence:
          - action: automation.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: automation.marstek_xom_ontladen
        alias: Duur
      - conditions:
          - condition: state
            entity_id: binary_sensor.my_cheapest_hours
            state:
              - "on"
          - alias: Prijsverschil
            condition: template
            value_template: >-
              {{state_attr('sensor.nordpool_kwh_nl_eur_3_10_021',
              'max')-state_attr('sensor.nordpool_kwh_nl_eur_3_10_021', 'min')
              >0.10}}
            enabled: true
        sequence:
          - action: automation.turn_on
            metadata: {}
            data: {}
            target:
              entity_id:
                - automation.marstek_xom_laden
        alias: Goedkoop
      - conditions:
          - condition: numeric_state
            entity_id: sensor.lilygo_rs485_marstek_battery_state_of_charge
            below: 15
        sequence:
          - action: automation.turn_on
            metadata: {}
            data: {}
            target:
              entity_id:
                - automation.marstek_xom_laden
          - wait_for_trigger:
              - type: battery_level
                device_id: ae7f494899ec0817d8915b4443a40dae
                entity_id: d20a68ea15411854283d17986fd17447
                domain: sensor
                trigger: device
                above: 20
                alias: Batterij meer dan 20% geladen
            timeout:
              hours: 1
              minutes: 0
              seconds: 0
              milliseconds: 0
          - action: automation.turn_off
            metadata: {}
            data:
              stop_actions: true
            target:
              label_id: marstek
          - action: automation.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: automation.marstek_netsafe
    default:
      - device_id: ae7f494899ec0817d8915b4443a40dae
        domain: select
        entity_id: ce57ba48c2ea3f52dd05e9142477587b
        type: select_option
        option: stop
      - action: automation.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
            - automation.marstek_netsafe
mode: single
